#!/bin/bash

[ $# -lt 1 ] && { printf "Usage: %s <package_name> \n" "$0"; exit 1; }

package_name="$1"

for package in $(fd 'package.json'); do
  for dep_type in dependencies devDependencies; do
    if jq -e --arg package_name "$package_name" ".${dep_type}[\$package_name]" "$package" > /dev/null; then
        printf "%s" "$(jq -r ".name" "$package")"
        [ "$dep_type" = "devDependencies" ] && printf " (devDep)\n" || printf "\n"
    fi
  done
done | column -t

exit 0