#!/bin/bash

# Check if the package name is provided as an argument
if [ $# -eq 0 ]; then
    echo "Usage: $0 <package_name>"
    exit 1
fi

# Package name provided as argument
package_name="$1"

printf "\n$package_name is used by:\n\n"
# Find package.json files excluding node_modules directories
find . -type d -name node_modules -prune -o -name package.json -exec grep -qE "\"($package_name)\" *: *\"[^\"]*\"" {} \; -exec jq -r '.name' {} \; | sed 's/^/ - /'
printf "\n"
