#!/bin/bash

# Check if the package name is provided as an argument
[ $# -eq 0 ] && { echo "Usage: $0 <package_name>"; exit 1; }

# Package name provided as argument
package_name="$1"

printf "\n$package_name is used by:\n\n"

# Find package.json files excluding node_modules directories
find . -type d -name node_modules -prune -o -name package.json -exec bash -c '
  file=$1
  package_name=$2
  for dep_type in dependencies devDependencies; do
    if jq -e --arg package_name "$package_name" ".$dep_type[\$package_name]" $file > /dev/null; then
      echo -n "- "
      if jq -e ".name" $file > /dev/null; then
        echo -n $(jq -r ".name" $file)
      else
        echo -n $file
      fi
      [ "$dep_type" = "devDependencies" ] && echo -e "\t\t(devDep)" || echo -e ""
    fi
  done
' bash {} "$package_name" \;

printf "\n"