#!/bin/bash

projects=$(fd .csproj)

for project in $projects; do
    userSecretIds=$(awk -F '[<>]' '/<UserSecretsId>/ {print $3}' "$project")

    if [ -z "$userSecretIds" ]; then
        continue
    fi

    project_basename=$(basename "$project")
    printf "%-80s%-100s\n" "$project_basename" "$(if [ -f "$HOME/.microsoft/usersecrets/$userSecretIds/secrets.json" ]; then echo "$HOME/.microsoft/usersecrets/$userSecretIds/secrets.json"; else echo "-"; fi)"

done
