#!/bin/bash

# This script lists all locations of secrets associated with .csproj files.

show_help() {
    echo "Usage: $(basename "$0") [--help | -h]"
    echo "       $(basename "$0") [PATH]"
    echo "  -h, --help          Display this help and exit."
    echo
    echo "This script searches for .csproj files in the specified PATH (or current directory if not provided)"
    echo "and its subdirectories, and lists the locations of secrets associated with them."
}

if [[ $1 == "--help" || $1 == "-h" ]]; then
    show_help
    exit 0
fi

path="${1:-.}"  # Default to current directory if no path is provided
projects=$(fd .csproj "$path")

for project in $projects; do
    userSecretIds=$(awk -F '[<>]' '/<UserSecretsId>/ {print $3}' "$project")

    if [ -z "$userSecretIds" ]; then
        continue
    fi

    project_basename=$(basename "$project")
    printf "%-80s%-100s\n" "$project_basename" "$(
        if [ -f "$HOME/.microsoft/usersecrets/$userSecretIds/secrets.json" ];
            then echo "$HOME/.microsoft/usersecrets/$userSecretIds/secrets.json";
            else echo "-";
        fi
    )"

done
