openapi: 3.0.0
info:
  title: Complex Test API
  version: 1.0.0
paths:
  /api/organizations/{orgId}/users:
    get:
      summary: Get users in organization
      parameters:
        - name: orgId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
    post:
      summary: Create user in organization
      parameters:
        - name: orgId
          in: path
          required: true
          schema:
            type: string
      responses:
        '201':
          description: Created
  /api/organizations/{orgId}/users/{userId}:
    get:
      summary: Get specific user in organization
      parameters:
        - name: orgId
          in: path
          required: true
          schema:
            type: string
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
    put:
      summary: Update user in organization
      parameters:
        - name: orgId
          in: path
          required: true
          schema:
            type: string
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
    delete:
      summary: Delete user from organization
      parameters:
        - name: orgId
          in: path
          required: true
          schema:
            type: string
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: No Content
  /api/projects/{projectId}/tasks:
    get:
      summary: Get project tasks
      parameters:
        - name: projectId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success</content>
</xai:function_call">/api/projects/{projectId}/tasks